version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - './data/clickhouse:/var/lib/clickhouse'
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9500:9000
      - 127.0.0.1:9009:9009

  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  collector:
    image: loghole/collector:latest
    build:
      context: ./collector
      dockerfile: ./docker/default/Dockerfile
    volumes:
      - ./database/:/db
    environment:
      - SERVER_HTTP_PORT=8080
      - SERVER_CERT=
      - SERVER_KEY=

      - ENABLE_AUTH=true
      - TOKEN_LIST=secret_token_1 secret_token_2

      - LOGGER_LEVEL=debug

      - CLICKHOUSE_URI=clickhouse:9000
      - CLICKHOUSE_USER=
      - CLICKHOUSE_DATABASE=logs
      - CLICKHOUSE_SCHEMA_PATH=/db/init.sql
    ports:
      - 50000:8080
    depends_on:
      - clickhouse

  dashboard:
    image: loghole/dashboard:latest
    build:
      context: ./dashboard
      dockerfile: ./docker/default/Dockerfile
    environment:
      - SERVICE_HTTP_PORT=8080
      - LOGGER_LEVEL=debug

      - CLICKHOUSE_URI=clickhouse:9000
      - CLICKHOUSE_USER=
      - CLICKHOUSE_DATABASE=logs
      - CLICKHOUSE_SCHEMA_PATH=/db/init.sql
    ports:
      - 8080:8080
    depends_on:
      - clickhouse

  populate_db:
    image: golang:1.14-alpine
    volumes:
      - ./dashboard/scripts/:/app
    working_dir: /app/populate_db/
    command: go run main.go
    environment:
      - COLLECTOR_URI=http://collector:8080
      - COLLECTOR_AUTH=secret_token_1
      - COUNT=1000
      - SLEEP=5s
    depends_on:
      - dashboard
